name: Eslint
on:
  push:

jobs:
  check_eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        sudo npm install -g eslint
    - run: eslint index.js --ext .js,.jsx,.ts,.tsx
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 17
    - run: |
        npm install
    - run: |
        npm run-script test